### ISSUE TITLE
程序能不能后台持续运行

### ISSUE THREAD

**Issue by uuip** [myfreeer/nop#1]
空程序能不能后台持续运行？
之前我写过
# include <windows.h>

int APIENTRY WinMain(HINSTANCE hInstance,HINSTANCE hPrevInstance,LPSTR lpCmdLine,int nCmdShow)
{ 
sleep(-1);
//GetMessage(NULL, NULL, 0, 0);
//SuspendThread(GetCurrentThread());
 return 0;
}
之前公司的一个监控软件会定时检测有没特定进程，没有的话就弹窗balabala，于是我模拟了一个空进程。
当时想了好久，也许SuspendThread开销还小点，一起研究下吧。
细节上1. 空进程后台持续运行，cpu和内存的占用越少越好；2. 留意下进程启动时鼠标会不会转圈圈；现在不管用sleep还是SuspendThread在程序启动时鼠标都会转圈圈。

**Comment by myfreeer** [comment]
如果你的监控软件没有被加壳，可以考虑用winhex查找需要的进程名并改为`smss.exe`(nt all)或`dwm.exe`(nt6.0+)

附测试结果（编译器：tcc x64 windows）：
`GetMessage(NULL, NULL, 0, 0);` 0% 0.5MB 这种鼠标转不到一圈，后面几种要转4～5圈

`Sleep(INFINITE);` 0% 0.2MB
`SleepEx(INFINITE, TRUE);` 0% 0.2MB
`WaitForSingleObject(GetCurrentThread(), INFINITE);` 0% 0.2MB
`WaitForSingleObject(OpenProcess(SYNCHRONIZE, FALSE, 4), INFINITE);` 0% 0.2MB

``` c
#include <windows.h>
typedef LONG (NTAPI *NtSuspendProcess)(IN HANDLE ProcessHandle);
int WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
{
    NtSuspendProcess pfnNtSuspendProcess = (NtSuspendProcess)GetProcAddress(
        GetModuleHandle("ntdll"), "NtSuspendProcess");
    pfnNtSuspendProcess(GetCurrentProcess());
    return 0;
}
```

0% 0.2MB

`for(;;);` 100%(单CPU) 0.2MB
`while(1);` 100%(单CPU) 0.2MB

**Comment by uuip** [comment]
是企业版的sep 会从服务器下载策略文件去检测，我尝试修改然导致计算机不能正常开机，才有此想法。
又搜了下还有
MsgWaitForMultipleObjects(1, NULL, FALSE, INFINITE, QS_ALLINPUT);  这个也不引起鼠标转圈圈。
它与
GetMessage(NULL, NULL, 0, 0);
谁占cpu少，或者与cpu交互的少？
毕竟是空进程，我想用最精练的代码去实现，可是我只懂的c++，对vc++不甚了了。

**Comment by myfreeer** [comment]
@uuip 在我这里用[tcc](http://download.savannah.gnu.org/releases/tinycc/)编译的话，这两种方法都不占用cpu(0%)，内存占用是0.5MB，但那些鼠标转圈的方法内存占用是0.2MB；

ps: 这是`c`，而不是`c++`
